---
title: "Simulation LDA"
author: "Sung Bongjung"
date: '2021 8 26 '
output: pdf_document
---

 In this note, we provide the code for simulation of LDA for breast cancer winsconsin diagonstic dataset. Since it takes a long time for the simulation of our propsosed estimator, approximately 6 hours, we shall provide only the data and simulation code. The rule for LDA and scheme is provided in the previous note. 

```{r}
#dataset 

wdbc=read.csv("wdbc.csv",header=FALSE)
true_status=wdbc[,1]

#1: case, 0: control
true_status[which(true_status=="M")]=1; true_status[which(true_status=="B")]=0
true_status=as.numeric(true_status)
wdbc=as.matrix(wdbc[,-1])
head(wdbc)
```

```{r, eval=FALSE}
#simulation code 

lda_cv=function(true_status,samp,partition){
  
  n=length(true_status); p=ncol(samp)  
  error_samp=numeric(length=partition);error_gl=numeric(length=partition)
  error_mpp=numeric(length=partition);error_map=numeric(length=partition)
  
  step.size=100
  tol=0.002
  P=matrix(1,p,p)
  diag(P)=0
  lam=0.06
  
  case=which(true_status==1); control=which(true_status==0)
  
  for(i in 1:partition){
    
    case_train=sort(sample(case,size=72,replace=FALSE))
    case_test=sort(setdiff(case,case_train))
    
    control_train=sort(sample(control,size=119,replace=FALSE))
    control_test=sort(setdiff(control,control_train))
    
    train=sort(c(case_train,control_train))
    test=sort(c(case_test,control_test))
    
    status_train=true_status[train]
    status_test=true_status[test]
    
    samp_train=samp[train,]
    samp_test=samp[test,]
    
    s1_train=samp[case_train,]; s0_train=samp[control_train,]
    
    #mean of class 1
    mu1=numeric(length=p)
    for(j in 1:72){
      mu1=mu1+as.numeric(s1_train[j,])
    }
    mu1=mu1/72
    
    #mean of class 0
    mu0=numeric(length=p)
    for(l in 1:119){
      mu0=mu0+as.numeric(s0_train[l,])
    }
    mu0=mu0/119
    
    #LDA rule for sample covariance matrix
    est_cov_samp=1/191*t(samp_train)%*%(diag(191)-1/191*rep(1,191)%*%t(rep(1,191)))%*%samp_train+0.1^3*diag(p)
    est_prec_samp=solve(est_cov_samp)
    
    #LDA rule for graphical lasso
    samp_cov=1/191*t(samp_train)%*%(diag(191)-1/191*rep(1,191)%*%t(rep(1,191)))%*%samp_train+0.001*diag(p)
    est_cov_gl=spcov(Sigma=samp_cov,S=samp_cov,lambda=lam*P,step.size=step.size,n.inner.steps=200,
                  thr.inner=0,tol.outer=tol,trace=1)$Sigma
    est_prec_gl=solve(est_cov_gl)
    
    #LDA rule for propsed estimator for both MPP and MAP
    #generate 12000 posterior sample after 3000 burn-in. 
    mcmc_samp=mcmc(191,samp_cov,1,191*0.05,0.1,12000,3000,0.65)
    mcmc_mpp=mpp(mcmc_samp)
    mcmc_map=mmp(mcmc_samp)
    
    est_cov_mpp=bcd_covariance2(samp_cov,191,1,191*0.05,10000,0.1^3,mcmc_mpp)
    est_prec_mpp=solve(est_cov_mpp)
    
    est_cov_map=bcd_covariance2(samp_cov,191,1,191*0.05,10000,0.1^3,mcmc_map)
    est_prec_map=solve(est_cov_map)
    
    #proportion of class j among train set. 
    p1=72/191
    p0=119/191
    
    error_temp_samp=0
    error_temp_gl=0
    error_temp_proposed_mpp=0
    error_temp_proposed_map=0
    
    for(ind in 1:378){
      est_samp=0; est_gl=0l est_mpp=0; est_map=0
      
      ob=samp_test[ind,]
      rule1_samp=as.numeric(t(ob)%*%est_prec_samp%*%mu1-1/2*t(mu1)%*%est_prec_samp%*%mu1+log(p1))
      rule0_samp=as.numeric(t(ob)%*%est_prec_samp%*%mu0-1/2*t(mu0)%*%est_prec_samp%*%mu0+log(p0))
      
      rule1_gl=as.numeric(t(ob)%*%est_prec_gl%*%mu1-1/2*t(mu1)%*%est_prec_gl%*%mu1+log(p1))
      rule0_gl=as.numeric(t(ob)%*%est_prec_gl%*%mu0-1/2*t(mu0)%*%est_prec_gl%*%mu0+log(p0))
      
      rule1_mpp=as.numeric(t(ob)%*%est_prec_mpp%*%mu1-1/2*t(mu1)%*%est_prec_mpp%*%mu1+log(p1))
      rule0_mpp=as.numeric(t(ob)%*%est_prec_mpp%*%mu0-1/2*t(mu0)%*%est_prec_mpp%*%mu0+log(p0))
      
      rule1_map=as.numeric(t(ob)%*%est_prec_map%*%mu1-1/2*t(mu1)%*%est_prec_map%*%mu1+log(p1))
      rule0_map=as.numeric(t(ob)%*%est_prec_map%*%mu0-1/2*t(mu0)%*%est_prec_map%*%mu0+log(p0))
      
      if(rule1_samp>rule0_samp){
        est_samp=1
      }
      if(rule1_gl>rule0_gl){
        est_gl=1
      }
      if(rule1_mpp>rule0_mpp){
        est_mpp=1
      }
      if(rule1_map>rule0_map){
        est_map=1
      }
      
      diff_samp=est_samp-status_test[ind]
      error_temp_samp=error_temp_samp+abs(diff)
    
      diff_gl=est_gl-status_test[ind]
      error_temp_gl=error_temp_gl+abs(diff)
      
      diff_mpp=est_mpp-status_test[ind]
      error_mpp_samp=error_temp_mpp+abs(diff)

      diff_map=est_map-status_test[ind]
      error_temp_map=error_temp_map+abs(diff)
    }
    error_samp[i]=error_temp_samp/378
    error_gl[i]=error_temp_gl/378
    error_mpp[i]=error_temp_mpp/378
    error_map[i]=error_temp_map/378
  }
  error=list(error_samp,error_gl,error_mpp,error_map)
  return(error)
}

#error 
error=lda_cv(true_status,wdbc,10)

#sample covariance matrix
mean(error[[1]]); sd(error[[1]])
#0.07698413; 0.01933812

#graphical lasso
mean(error[[2]]); sd(error[[2]])
# 0.07222222; 0.01670605

#proposed (MPP)
mean(error[[3]]); sd(error[[3]])
#0.06613757; 0.01635521

#proposed (MAP)
mean(error[[4]]); sd(error[[4]])
#0.06613757; 0.01635521
```